// <auto-generated />
using System;
using BrasilBurger.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrasilBurger.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221115732_FixEtatStock")]
    partial class FixEtatStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrasilBurger.Web.Entity.Burger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EtatStock")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etatstock");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<double>("Prix")
                        .HasColumnType("double precision")
                        .HasColumnName("prix");

                    b.Property<string>("UrlImage")
                        .HasColumnType("text")
                        .HasColumnName("url_image");

                    b.HasKey("Id");

                    b.ToTable("burger", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("text")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("EtatCmd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etat_cmd");

                    b.Property<double?>("FraisLivraison")
                        .HasColumnType("double precision")
                        .HasColumnName("frais_livraison");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.Property<int?>("IdGestionnaire")
                        .HasColumnType("integer")
                        .HasColumnName("id_gestionnaire");

                    b.Property<int?>("IdLivreur")
                        .HasColumnType("integer")
                        .HasColumnName("id_livreur");

                    b.Property<int?>("IdZone")
                        .HasColumnType("integer")
                        .HasColumnName("id_zone");

                    b.Property<string>("LieuConsommation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lieu_consommation");

                    b.Property<double>("MontantTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("montant_total");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("commande", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.CommandeBurger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBurger")
                        .HasColumnType("integer")
                        .HasColumnName("id_burger");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("id_commande");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("double precision")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.ToTable("commande_burger", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.CommandeMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("id_commande");

                    b.Property<int>("IdMenu")
                        .HasColumnType("integer")
                        .HasColumnName("id_menu");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("double precision")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.ToTable("commande_menu", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.Complement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EtatStock")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etatstock");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<double>("Prix")
                        .HasColumnType("double precision")
                        .HasColumnName("prix");

                    b.Property<string>("UrlImage")
                        .HasColumnType("text")
                        .HasColumnName("url_image");

                    b.HasKey("Id");

                    b.ToTable("complement", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EtatStock")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etatstock");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<double>("PrixTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("prix_total");

                    b.Property<string>("UrlImage")
                        .HasColumnType("text")
                        .HasColumnName("url_image");

                    b.HasKey("Id");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.MenuBurger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBurger")
                        .HasColumnType("integer")
                        .HasColumnName("id_burger");

                    b.Property<int>("IdMenu")
                        .HasColumnType("integer")
                        .HasColumnName("id_menu");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.ToTable("menu_burger", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.MenuComplement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdComplement")
                        .HasColumnType("integer")
                        .HasColumnName("id_complement");

                    b.Property<int>("IdMenu")
                        .HasColumnType("integer")
                        .HasColumnName("id_menu");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.ToTable("menu_complement", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("id_commande");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<double>("Montant")
                        .HasColumnType("double precision")
                        .HasColumnName("montant");

                    b.HasKey("Id");

                    b.ToTable("paiement", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Entity.Commande", b =>
                {
                    b.HasOne("BrasilBurger.Web.Entity.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
