
driver=org.postgresql.Driver


url=jdbc:postgresql://ep-sweet-salad-a4du5jwo-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require


user=neondb_owner

password=npg_gxJ6RP3fELoT

